name: backend
channels:
  - defaults
dependencies:
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - django=2.2.5=py37_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_2
  - pip=19.2.3=py37_0
  - python=3.7.4=h359304d_1
  - pytz=2019.2=py_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.2.0=py37_0
  - sqlite=3.30.0=ha441bb4_0
  - sqlparse=0.3.0=py_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - djangorestframework==3.10.3
prefix: //miniconda3/envs/backend

